[connections.supabase]
SUPABASE_URL="https://kswgpttjtccdpvnbzijc.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzd2dwdHRqdGNjZHB2bmJ6aWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ0ODEsImV4cCI6MjA2NzkxMDQ4MX0.4o4zZkeqVmN7wslYK-FN8n8HFjGgW5PvoVwyt2Czl34"