[connections.supabase]
SUPABASE_URL="https://kswgpttjtccdpvnbzijc.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzd2dwdHRqdGNjZHB2bmJ6aWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ0ODEsImV4cCI6MjA2NzkxMDQ4MX0.4o4zZkeqVmN7wslYK-FN8n8HFjGgW5PvoVwyt2Czl34"

[cookies]
COOKIE_MASTER_KEY = "qHOQYRxp-4IR0ChzLbEt6nI1GP7TQ0Al8_wmQqJ28EY"

[ultramsg.rafael]
ID="instance134627"
TOKEN="pej3tggtog5pu7sn"
PHONE_NUMBER="+5564992517702"

# [ultramsg.welton]
# ID="instance134627"
# TOKEN="pej3tggtog5pu7sn"
# PHONE_NUMBER="+5562981204899"

[assertiva]
ASSERTIVA_CLIENT_ID="9PC3NNViH1MQ9NaHgd+DOs/vzoffpqP6S6qhWoXo/Rclm2hHnTU+HernsG5rk4B6VHE/gqdkCr92q9EkLcbQNw=="
ASSERTIVA_SECRET="yle+lCZCnqfELYcL4nUpaCnNBkOKtsPW5b9Fn+v4fIMEFJ8n5aZxCp6Od3Stf0VzuCyYXITAAH+5jYJVpj1zcw=="