[connections.supabase]
SUPABASE_URL="https://kswgpttjtccdpvnbzijc.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzd2dwdHRqdGNjZHB2bmJ6aWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzQ0ODEsImV4cCI6MjA2NzkxMDQ4MX0.4o4zZkeqVmN7wslYK-FN8n8HFjGgW5PvoVwyt2Czl34"

[cookies]
COOKIE_MASTER_KEY = "qHOQYRxp-4IR0ChzLbEt6nI1GP7TQ0Al8_wmQqJ28EY"

[ultramsg_1]
ID="instance134627"
TOKEN="pej3tggtog5pu7sn"
PHONE_NUMBER="+5564992517702"